plugins {
	id 'java'
	id 'org.springframework.boot' version '3.0.1' // Ensure you're using a stable version
	id 'io.spring.dependency-management' version '1.1.4'
}

springBoot {
	mainClass = 'com.discordapi.SpringRunner' // Replace with the fully qualified name of your main class
}

group = 'com.discordapi'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '17'
	targetCompatibility = '17'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'com.discord4j:discord4j-core:3.2.6'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.projectlombok:lombok:1.18.30'  // Use the latest stable version of Lombok
	annotationProcessor 'org.projectlombok:lombok:1.18.30'  // Lombok annotation processor
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation 'com.fasterxml.jackson.core:jackson-databind'
	implementation group: 'net.dv8tion', name: 'JDA', version: '5.0.0-alpha.22'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.register('createDist', Zip) {
	from bootJar
	into('lib') {
		from configurations.runtimeClasspath
	}
	archiveFileName = 'churchill_quotes_app.zip'
}

bootRun {
	main = 'com.discordapi.SpringRunner'
}

createDist.dependsOn build